### ISSUE TITLE
Latest 1.20.1 Forge version crashes to desktop

### ISSUE THREAD

**Issue by ModernGamingWorld** [TathanDev/StarWarsPlanets-AdAstra#18]
Time: 2024-08-21 16:13:36
Description: Mod loading error has occurred

java.lang.Exception: Mod Loading has failed
	at net.minecraftforge.logging.CrashReportExtender.dumpModLoadingCrashReport(CrashReportExtender.java:60) ~[forge-1.20.1-47.3.7-universal.jar%231517!/:?] {re:mixin,re:classloading,pl:mixin:APP:connectormod.mixins.json:CrashReportExtenderMixin from mod connectormod,pl:mixin:APP:embeddium.mixins.json:core.CrashReportExtenderMixin from mod embeddium,pl:mixin:A}
	at net.minecraftforge.client.loading.ClientModLoader.completeModLoading(ClientModLoader.java:138) ~[forge-1.20.1-47.3.7-universal.jar%231517!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.lambda$new$4(Minecraft.java:571) ~[client-1.20.1-20230612.114412-srg.jar%231512!/:?] {re:mixin,pl:accesstransformer:B,pl:connector_pre_launch:A,pl:runtimedistcleaner:A,re:computing_frames,pl:accesstransformer:B,pl:connector_pre_launch:A,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:A,pl:connector_pre_launch:A,pl:runtimedistcleaner:A}
	at net.minecraft.Util.m_137521_(Util.java:421) ~[client-1.20.1-20230612.114412-srg.jar%231512!/:?] {re:mixin,pl:accesstransformer:B,pl:connector_pre_launch:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:bettermineshafts.mixins.json:SuppressLogMixin from mod bettermineshafts,pl:mixin:APP:kubejs-common.mixins.json:UtilMixin from mod kubejs,pl:mixin:APP:ftbchunks-common.mixins.json:UtilMixin from mod ftbchunks,pl:mixin:APP:smoothboot.mixins.json:UtilMixin from mod smoothboot,pl:mixin:APP:yungsbridges.mixins.json:SuppressLogMixin from mod yungsbridges,pl:mixin:A,pl:connector_pre_launch:A}
	at net.minecraft.client.Minecraft.lambda$new$5(Minecraft.java:564) ~[client-1.20.1-20230612.114412-srg.jar%231512!/:?] {re:mixin,pl:accesstransformer:B,pl:connector_pre_launch:A,pl:runtimedistcleaner:A,re:computing_frames,pl:accesstransformer:B,pl:connector_pre_launch:A,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:A,pl:connector_pre_launch:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.gui.screens.LoadingOverlay.m_88315_(LoadingOverlay.java:138) ~[client-1.20.1-20230612.114412-srg.jar%231512!/:?] {re:mixin,pl:accesstransformer:B,pl:connector_pre_launch:A,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:kubejs-common.mixins.json:LoadingOverlayMixin from mod kubejs,pl:mixin:APP:fancymenu.mixins.json:client.MixinLoadingOverlay from mod fancymenu,pl:mixin:APP:drippyloadingscreen.mixins.json:client.IMixinLoadingOverlay from mod drippyloadingscreen,pl:mixin:APP:drippyloadingscreen.mixins.json:client.MixinLoadingOverlay from mod drippyloadingscreen,pl:mixin:A,pl:connector_pre_launch:A,pl:runtimedistcleaner:A}
	at net.minecraftforge.client.loading.ForgeLoadingOverlay.handler$iao000$drippyloadingscreen$cancelForgeCustomLoadingOverlayRenderingDrippy(ForgeLoadingOverlay.java:1027) ~[forge-1.20.1-47.3.7-universal.jar%231517!/:?] {re:mixin,re:classloading,pl:mixin:A}
	at net.minecraftforge.client.loading.ForgeLoadingOverlay.m_88315_(ForgeLoadingOverlay.java) ~[forge-1.20.1-47.3.7-universal.jar%231517!/:?] {re:mixin,re:classloading,pl:mixin:A}
	at net.minecraft.client.renderer.GameRenderer.m_109093_(GameRenderer.java:954) ~[client-1.20.1-20230612.114412-srg.jar%231512!/:?] {re:mixin,pl:accesstransformer:B,pl:connector_pre_launch:A,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:moonlight-common.mixins.json:GameRendererMixin from mod moonlight,pl:mixin:APP:pehkui.mixins.json:reach.client.compat1202minus.GameRendererMixin from mod pehkui,pl:mixin:APP:immediatelyfast-common.mixins.json:core.compat.MixinGameRenderer from mod immediatelyfast,pl:mixin:APP:AdditionalAdditions.mixins.json:GameRendererMixin from mod additionaladditions,pl:mixin:APP:justzoom.mixins.json:client.MixinGameRenderer from mod justzoom,pl:mixin:APP:flickerfix.mixins.json:MixinGameRenderer from mod flickerfix,pl:mixin:APP:forcecraft.mixins.json:GameRendererMixin from mod forcecraft,pl:mixin:APP:mixins.reach-entity-attributes.json:client.GameRendererMixin from mod reach_entity_attributes,pl:mixin:APP:vinery-common.mixins.json:GameRendererMixin from mod vinery,pl:mixin:APP:fairylights.mixins.json:GameRendererMixin from mod fairylights,pl:mixin:APP:mixins.oculus.json:GameRendererAccessor from mod oculus,pl:mixin:APP:mixins.oculus.json:MixinGameRenderer from mod oculus,pl:mixin:APP:mixins.oculus.json:MixinModelViewBobbing from mod oculus,pl:mixin:APP:tombstone.mixins.json:GameRendererMixin from mod tombstone,pl:mixin:APP:embeddiumplus.mixin.json:darkness.GameRendererMixin from mod embeddiumplus,pl:mixin:APP:entity_model_features-common.mixins.json:MixinGameRenderer from mod entity_model_features,pl:mixin:APP:brewery-common.mixins.json:GameRendererMixin from mod brewery,pl:mixin:APP:mixins.artifacts.common.json:item.wearable.nightvisiongoggles.client.GameRendererMixin from mod artifacts,pl:mixin:APP:fancymenu.forge.mixins.json:client.MixinForgeGameRenderer from mod fancymenu,pl:mixin:APP:fastload.mixins.json:client.GameRendererMixin from mod fastload,pl:mixin:APP:pehkui.mixins.json:client.compat1193plus.GameRendererMixin from mod pehkui,pl:mixin:APP:pehkui.mixins.json:client.compat1204minus.compat1193plus.GameRendererMixin from mod pehkui,pl:mixin:APP:ars_nouveau.mixins.json:GameRendererMixin from mod ars_nouveau,pl:mixin:APP:mixins.cofhcore.json:GameRendererMixin from mod cofh_core,pl:mixin:APP:zeta_forge.mixins.json:client.GameRenderMixin from mod zeta,pl:mixin:APP:cutthrough.common.mixins.json:client.GameRendererMixin from mod cutthrough,pl:mixin:APP:alexscaves.mixins.json:client.GameRendererMixin from mod alexscaves,pl:mixin:APP:supplementaries-common.mixins.json:GameRendererMixin from mod supplementaries,pl:mixin:APP:create.mixins.json:accessor.GameRendererAccessor from mod create,pl:mixin:APP:create.mixins.json:client.GameRendererMixin from mod create,pl:mixin:APP:embeddium.mixins.json:features.gui.hooks.console.GameRendererMixin from mod embeddium,pl:mixin:APP:mixins.oculus.json:MixinGameRenderer_NightVisionCompat from mod oculus,pl:mixin:APP:securitycraft.mixins.json:camera.GameRendererMixin from mod securitycraft,pl:mixin:APP:forge-badoptimizations.mixins.json:tick.MixinGameRenderer from mod (unknown),pl:mixin:A,pl:connector_pre_launch:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91383_(Minecraft.java:1146) ~[client-1.20.1-20230612.114412-srg.jar%231512!/:?] {re:mixin,pl:accesstransformer:B,pl:connector_pre_launch:A,pl:runtimedistcleaner:A,re:computing_frames,pl:accesstransformer:B,pl:connector_pre_launch:A,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:A,pl:connector_pre_launch:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91374_(Minecraft.java:718) ~[client-1.20.1-20230612.114412-srg.jar%231512!/:?] {re:mixin,pl:accesstransformer:B,pl:connector_pre_launch:A,pl:runtimedistcleaner:A,re:computing_frames,pl:accesstransformer:B,pl:connector_pre_launch:A,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:A,pl:connector_pre_launch:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:218) ~[forge-47.3.7.jar:?] {re:mixin,pl:connector_pre_launch:A,pl:runtimedistcleaner:A,re:classloading,pl:mixin:APP:flywheel.mixins.json:ClientMainMixin from mod flywheel,pl:mixin:APP:smoothboot.mixins.json:client.MainMixin from mod smoothboot,pl:mixin:A,pl:connector_pre_launch:A,pl:runtimedistcleaner:A}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:?] {}
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:?] {re:mixin}
	at net.minecraftforge.fml.loading.targets.CommonLaunchHandler.runTarget(CommonLaunchHandler.java:111) ~[fmlloader-1.20.1-47.3.7.jar:?] {}
	at net.minecraftforge.fml.loading.targets.CommonLaunchHandler.clientService(CommonLaunchHandler.java:99) ~[fmlloader-1.20.1-47.3.7.jar:?] {}
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$makeService$0(CommonClientLaunchHandler.java:25) ~[fmlloader-1.20.1-47.3.7.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:108) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:78) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141) ~[bootstraplauncher-1.1.2.jar:?] {}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Suspected Mod: 
	Drippy Loading Screen (drippyloadingscreen), Version: 3.0.1
		Mixin class: de.keksuccino.drippyloadingscreen.mixin.mixins.forge.client.MixinForgeLoadingOverlay
		Target: net.minecraftforge.client.loading.ForgeLoadingOverlay
		at TRANSFORMER/forge@47.3.7/net.minecraftforge.client.loading.ForgeLoadingOverlay.handler$iao000$drippyloadingscreen$cancelForgeCustomLoadingOverlayRenderingDrippy(ForgeLoadingOverlay.java:1027)
Stacktrace:
	at java.lang.Class.getConstructor0(Unknown Source) ~[?:?] {re:mixin}
-- MOD swplanets --
Details:
	Mod File: /E:/CurseForge/Instances/Monumental Experience (1)/mods/swplanets-forge-1.20.1-1.4.3.jar
	Failure message: Star Wars Planet (swplanets) has failed to load correctly
		java.lang.NoSuchMethodException: fr.tathan.swplanets.forge.NeoForgeSWPlanets.<init>()
	Mod Version: 1.4.3
	Mod Issue URL: https://github.com/TathanDev/StarWarsPlanets-AdAstra/issues
	Exception message: java.lang.NoSuchMethodException: fr.tathan.swplanets.forge.NeoForgeSWPlanets.<init>()
Stacktrace:
	at java.lang.Class.getConstructor0(Unknown Source) ~[?:?] {re:mixin}
	at java.lang.Class.getDeclaredConstructor(Unknown Source) ~[?:?] {re:mixin}
	at net.minecraftforge.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.java:70) ~[javafmllanguage-1.20.1-47.3.7.jar%231514!/:?] {}
	at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$4(ModContainer.java:124) ~[fmlcore-1.20.1-47.3.7.jar%231513!/:?] {re:mixin}
	at java.util.concurrent.CompletableFuture$AsyncRun.run(Unknown Source) ~[?:?] {}
	at java.util.concurrent.CompletableFuture$AsyncRun.exec(Unknown Source) ~[?:?] {}
	at java.util.concurrent.ForkJoinTask.doExec(Unknown Source) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(Unknown Source) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool.scan(Unknown Source) ~[?:?] {re:mixin,re:computing_frames}
	at java.util.concurrent.ForkJoinPool.runWorker(Unknown Source) ~[?:?] {re:mixin,re:computing_frames}
	at java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source) ~[?:?] {re:mixin}

**Comment by TathanDev** [comment]
Thanks for the report i'll fix it today !

**Comment by TathanDev** [comment]
Fixed in the new version 
[https://legacy.curseforge.com/minecraft/mc-mods/star-wars-planets-ad-astra/files/5653512](https://legacy.curseforge.com/minecraft/mc-mods/star-wars-planets-ad-astra/files/5653512)
